name: littlethings
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47086
title: 'The Little Things | Gratitude'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#729dc8'
    - '#adc7e0'
    - '#120606'
    - '#983002'
    - '#fee3b5'
  brandStrength: 0.75
  lightness: 0.5394956234376878
  saturation: 0.30608658329583704
  rhythmicContrast: 0.07809087634086609
purpose: []
